print("winter".islower())
print("winter ^^&2525".islower())
print("Winter".islower())
print()
print("SUMMER".isupper())
print("Summer".isupper())
print("SUMMER 83*&(*:".isupper())
print()
print("The Four Seasons".istitle())
print("The 4 Seasons".istitle())
print("The 4 seasons".istitle())
print()
print("area".isalpha())
print("area 51".isalpha())
print("Area *&^*(&%".isalpha())
print()
print("area".isnumeric())
print("area 51".isnumeric())
print("51".isnumeric())
print("51(*&^*&%$".isnumeric())
print()
print("Area51".isalnum())
print("Area 51".isalnum())