print("datamine"[1:5])
print()
colors = ["yellow", "green", "black", "fuschia", "brown", "orange"]
print(colors[1:4])
print(colors[0:1])
print(colors[:4])
print(colors[2:])
print(colors[-6:-2])
print(colors[-5:])
print(colors[::2])
print(colors[::-1])